version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-email
    environment:
      POSTGRES_DB: db_email
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
